heat_template_version: 2013-05-23

description: Simple template to deploy a 2 tier web application

resources:
  wordpress_app:
    type: OS::Nova::Server
    properties:
      image: "Ubuntu 14.04 LTS"
      flavor: Standard
      networks:
        - network: "DevOps Lab"
      security_groups: ["Allow All"]

  wordpress_db:
    type: OS::Nova::Server
    properties:
      image: "Ubuntu 14.04 LTS"
      flavor: Standard
      networks:
        - network: "DevOps Lab"
      security_groups: ["Allow All"]
